graph:
  nodes:
    - id: start
      type: start
      config:
        keys:
          - key_1
          - key_2
          - key_3
    - id: end
      type: end
      config:
        keys:
          - output_key
    - id: stage1
      type: stage
      stage: Stage1
      config:
        on_failure: route
    - id: stage2
      type: stage
      stage: Stage2
      config: {}
    - id: stage3
      type: stage
      stage: Stage3
      config: {}
    - id: stage4
      type: stage
      stage: Stage4
      config: {}
  edges:
    - from:
        node: start
        port: out
      to:
        node: stage1
        port: in
    - from:
        node: stage1
        port: out
      to:
        node: stage2
        port: in
    - from:
        node: stage1
        port: fail
      to:
        node: stage3
        port: in
    - from:
        node: stage3
        port: out
      to:
        node: stage4
        port: in
    - from:
        node: stage2
        port: out
      to:
        node: stage4
        port: in
    - from:
        node: stage4
        port: out
      to:
        node: end
        port: in
  comments:
    - id: comment
      text: Some comment
      color: green
ui:
  viewport:
    x: -8
    'y': 68
    zoom: 1.03
  node_positions:
    start:
      x: 183
      'y': 441
    end:
      x: 1166
      'y': 511
    stage1:
      x: 400
      'y': 489
    stage2:
      x: 652
      'y': 423
    stage3:
      x: 597
      'y': 575
    stage4:
      x: 924
      'y': 526
    comment:
      x: 637
      'y': 305
